# Generated by Django 6.0 on 2025-12-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='engineer_remarks',
            field=models.TextField(blank=True),
        ),
    ]
