# Generated by Django 6.0 on 2025-12-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='location',
            field=models.CharField(default='ABM Warehouse', max_length=100),
        ),
        migrations.AddField(
            model_name='stock',
            name='min_stock_level',
            field=models.IntegerField(default=0),
        ),
    ]
