# Generated by Django 6.0 on 2025-12-12 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_stock_location_stock_min_stock_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='quantity',
            new_name='current_quantity',
        ),
    ]
