# Generated by Django 6.0 on 2025-12-13 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_rename_quantity_stock_current_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='min_stock_level',
            field=models.IntegerField(default=10),
        ),
    ]
