# Generated by Django 6.0 on 2025-12-13 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_alter_product_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='desc',
        ),
    ]
