# Generated by Django 6.0 on 2025-12-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_remove_product_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='total_stock',
            field=models.IntegerField(default=100),
        ),
    ]
