# Generated by Django 6.0 on 2025-12-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_stock_total_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='current_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
