# Generated by Django 6.0 on 2025-12-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0011_alter_stock_current_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='current_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='min_stock_level',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='total_stock',
            field=models.PositiveIntegerField(),
        ),
    ]
