# Generated by Django 6.0 on 2025-12-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0012_alter_stock_current_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='total_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
