# Generated by Django 6.0 on 2025-12-13 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0014_alter_order_order_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_by',
            new_name='dealer',
        ),
    ]
