# Generated by Django 6.0 on 2025-12-15 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0015_rename_order_by_order_dealer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax',
            field=models.DecimalField(choices=[('18', '18'), ('12', '12'), ('5', '5')], decimal_places=2, default=18, max_digits=2),
        ),
    ]
