# Generated by Django 6.0 on 2025-12-15 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0017_alter_product_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
