# Generated by Django 6.0 on 2025-12-17 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0018_orderitem_gst_rate_orderitem_unit_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dealer',
        ),
        migrations.AddField(
            model_name='order',
            name='bill_building',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='bill_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='bill_country',
            field=models.CharField(blank=True, default='india', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='bill_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='bill_zip',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='order',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='gstin',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='shipp_building',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='shipp_city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='shipp_country',
            field=models.CharField(default='india', max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='shipp_state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='shipp_zip',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp.order'),
        ),
    ]
