# Generated by Django 6.0 on 2025-12-20 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0019_remove_order_dealer_order_bill_building_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='tax_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
