# Generated by Django 6.0 on 2025-12-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0020_order_grand_total_order_sub_total_order_tax_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
