# Generated by Django 6.0 on 2025-12-29 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0022_order_courier_order_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='courier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
