# Generated by Django 6.0 on 2025-12-30 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0023_alter_order_courier'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dealer',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'dealer'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dealer_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
