# Generated by Django 6.0 on 2025-12-30 07:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0024_order_dealer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dealer',
            field=models.ForeignKey(limit_choices_to={'role': 'dealer'}, on_delete=django.db.models.deletion.PROTECT, related_name='dealer_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
