# Generated by Django 6.0 on 2026-01-08 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_dealer_user'),
        ('erp', '0027_order_sales_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dealer',
            field=models.ForeignKey(limit_choices_to={'role': 'dealer'}, on_delete=django.db.models.deletion.PROTECT, related_name='dealer_orders', to='accounts.dealer'),
        ),
    ]
