# Generated by Django 6.0 on 2026-01-12 05:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_dealer_user'),
        ('erp', '0028_alter_order_dealer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dealer',
            field=models.ForeignKey(limit_choices_to={'user__role': 'dealer'}, on_delete=django.db.models.deletion.PROTECT, related_name='dealer_orders', to='accounts.dealer'),
        ),
    ]
