# Generated by Django 6.0 on 2026-01-15 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0029_alter_order_dealer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceRequest',
        ),
    ]
