# Generated by Django 6.0 on 2026-02-06 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_is_suspended'),
        ('erp', '0030_delete_servicerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dealer',
            field=models.ForeignKey(blank=True, limit_choices_to={'user__role': 'dealer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealer_orders', to='accounts.dealer'),
        ),
    ]
