# Generated by Django 6.0 on 2026-02-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0031_alter_order_dealer'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('bank', 'Bank Transfer')], max_length=20, null=True),
        ),
    ]
