# Generated by Django 6.0 on 2026-02-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0032_order_payment_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_model',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
