# Generated by Django 6.0 on 2026-02-10 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0033_alter_product_product_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='new_stock_shippment',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stock',
            name='current_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
