# Generated by Django 6.0 on 2026-02-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0034_stock_new_stock_shippment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='last_shipment_qty',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
