# Generated by Django 6.0 on 2026-02-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0035_stock_last_shipment_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer')], max_length=20, null=True),
        ),
    ]
