# Generated by Django 6.0 on 2026-02-16 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0037_alter_order_payment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
