# Generated by Django 6.0 on 2026-01-03 09:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=150)),
                ('product_model', models.CharField(max_length=100)),
                ('product_serial', models.CharField(max_length=100)),
                ('purchase_date', models.DateField()),
                ('issue_desc', models.TextField()),
                ('issue_image', models.ImageField(blank=True, upload_to='service/images/')),
                ('issue_video', models.FileField(blank=True, upload_to='service/videos/')),
                ('status', models.CharField(choices=[('raised', 'Raised'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('waiting_spare', 'Waiting for Spare'), ('completed', 'Completed'), ('closed', 'closed')], default='raised', max_length=20)),
                ('warranty', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('assigned_engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET, related_name='assigned_engineer', to=settings.AUTH_USER_MODEL)),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_logs', to='services.servicerequest')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='services.servicerequest')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resolution_summary', models.TextField()),
                ('engineer_remark', models.CharField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('closed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_service', to=settings.AUTH_USER_MODEL)),
                ('service_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='closure', to='services.servicerequest')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='service/attachment/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='services.servicerequest')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceSparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=150)),
                ('part_number', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('sent_date', models.DateField(blank=True, null=True)),
                ('received', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_parts', to='services.servicerequest')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=25)),
                ('new_status', models.CharField(max_length=25)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='services.servicerequest')),
            ],
        ),
    ]
