# Generated by Django 6.0 on 2026-01-05 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicerequest_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='order',
        ),
    ]
