# Generated by Django 6.0 on 2026-01-13 09:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_servicerequest_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesparepart',
            name='received',
        ),
        migrations.RemoveField(
            model_name='servicesparepart',
            name='received_date',
        ),
        migrations.RemoveField(
            model_name='servicesparepart',
            name='sent_date',
        ),
        migrations.AddField(
            model_name='servicesparepart',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicesparepart',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicesparepart',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('returned', 'Returned'), ('not_returned', 'Not Returned')], default='assigned', max_length=20),
        ),
        migrations.AlterField(
            model_name='servicesparepart',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
