# Generated by Django 6.0 on 2026-01-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_remove_servicesparepart_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('raised', 'Raised'), ('assigned', 'Assigned'), ('waiting_spare', 'Waiting for Spare'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('closed', 'closed')], default='raised', max_length=20),
        ),
    ]
