# Generated by Django 6.0 on 2026-01-14 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_servicerequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesparepart',
            name='cost',
        ),
    ]
