# Generated by Django 6.0 on 2026-01-16 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0030_delete_servicerequest'),
        ('services', '0009_servicerequest_order_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='erp.order'),
        ),
    ]
