# Generated by Django 6.0 on 2026-01-17 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_servicerequest_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
