# Generated by Django 6.0 on 2026-01-21 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_alter_servicerequest_purchase_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SparePartRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=255)),
                ('part_number', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('dispatched', 'Dispatched'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('courier_partner', models.CharField(blank=True, max_length=100, null=True)),
                ('docket_number', models.CharField(blank=True, max_length=100, null=True)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(limit_choices_to={'sub_employee_role': 'service'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_requests', to='services.servicerequest')),
            ],
        ),
        migrations.CreateModel(
            name='SparePartReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courier_partner', models.CharField(max_length=100)),
                ('docket_number', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('engineer', models.ForeignKey(limit_choices_to={'sub_employee_role': 'service'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_returns', to='services.servicerequest')),
            ],
        ),
    ]
