# Generated by Django 6.0 on 2026-01-21 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_sparepartrequest_sparepartreturn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepartrequest',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('requested', 'Requested'), ('dispatched', 'Dispatched'), ('received', 'Received'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
