# Generated by Django 6.0 on 2026-01-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_alter_sparepartrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepartrequest',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
