# Generated by Django 6.0 on 2026-01-23 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_sparepartrequest_received_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepartreturn',
            name='part_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sparepartreturn',
            name='part_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sparepartreturn',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='sparepartreturn',
            name='remark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
