# Generated by Django 6.0 on 2026-02-07 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_sparepartreturn_part_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('bank', 'Bank Transfer')], max_length=20, null=True),
        ),
    ]
