# Generated by Django 6.0 on 2026-02-07 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_servicerequest_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='company_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='gstin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='warranty_file',
            field=models.FileField(blank=True, null=True, upload_to='service/warranty/'),
        ),
    ]
