# Generated by Django 6.0 on 2026-02-07 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_servicerequest_company_name_servicerequest_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
