# Generated by Django 6.0 on 2026-02-12 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_servicerequest_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('bank transfer', 'Bank Transfer')], max_length=20, null=True),
        ),
    ]
