# Generated by Django 6.0 on 2026-02-14 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_alter_servicerequest_payment_mode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerequest',
            old_name='warranty_file',
            new_name='proof_of_warranty',
        ),
    ]
