# Generated by Django 6.0 on 2026-02-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_rename_warranty_file_servicerequest_proof_of_warranty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceclosure',
            name='engineer_remark',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
