# Generated by Django 6.0 on 2026-03-09 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_sparepartinventory_remove_sparepartrequest_part_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepartinventory',
            name='location',
            field=models.CharField(blank=True, default='ABM', max_length=100, null=True),
        ),
    ]
