# Generated by Django 6.0 on 2026-03-10 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0023_alter_sparepartinventory_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=150)),
                ('part_number', models.CharField(max_length=100, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='sparepartrequest',
            name='spare_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='services.sparepart'),
        ),
        migrations.CreateModel(
            name='SparePartStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_stock_level', models.PositiveIntegerField(default=5)),
                ('new_stock_shipment', models.PositiveIntegerField(default=0)),
                ('total_stock', models.PositiveIntegerField(default=0)),
                ('last_shipment_qty', models.PositiveIntegerField(default=0)),
                ('current_quantity', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(default='ABM Warehouse', max_length=100)),
                ('spare_part', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='services.sparepart')),
            ],
        ),
    ]
