# Generated by Django 6.0 on 2026-03-13 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0024_sparepart_alter_sparepartrequest_spare_part_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SparePartInventory',
        ),
    ]
