# Generated by Django 6.0 on 2026-03-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0025_delete_sparepartinventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepartrequest',
            name='part_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
