# Generated by Django 6.0 on 2026-03-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0026_sparepartrequest_part_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sparepart',
            name='part_number',
            field=models.CharField(max_length=100),
        ),
    ]
