# Generated by Django 6.0 on 2025-12-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sub_employee_role',
            field=models.CharField(blank=True, choices=[('sales', 'Sales'), ('service', 'service'), ('inventory', 'inventory'), ('dispatch', 'dispatch')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('director', 'Director'), ('employee', 'Employee'), ('dealer', 'Dealer')], max_length=20),
        ),
    ]
