# Generated by Django 6.0 on 2025-12-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_sub_employee_role_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('director', 'Director'), ('employee', 'Employee'), ('dealer', 'Dealer')], max_length=20),
        ),
    ]
