# Generated by Django 6.0 on 2026-01-01 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firm_name', models.CharField(max_length=255)),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True)),
                ('bill_address_line1', models.CharField(max_length=255)),
                ('bill_address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('bill_city', models.CharField(max_length=100)),
                ('bill_state', models.CharField(max_length=100)),
                ('bill_pincode', models.CharField(max_length=6)),
                ('bill_country', models.CharField(default='India', max_length=50)),
                ('ship_address_line1', models.CharField(max_length=255)),
                ('ship_address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('ship_city', models.CharField(max_length=100)),
                ('ship_state', models.CharField(max_length=100)),
                ('ship_pincode', models.CharField(max_length=6)),
                ('ship_country', models.CharField(default='India', max_length=50)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
