# Generated by Django 6.0 on 2026-02-07 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_is_suspended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sub_employee_role',
            field=models.CharField(blank=True, choices=[('sales', 'Sales'), ('service', 'Service'), ('engineer', 'Engineer'), ('inventory', 'Inventory'), ('dispatch', 'Dispatch')], max_length=20, null=True),
        ),
    ]
